update scripts

diff --git a/bin/compiler b/bin/compiler
--- a/bin/compiler
+++ b/bin/compiler
@@ -1,4 +1,5 @@
 #!/bin/sh
+set -x
 
 # This script will compile or run another finishing operation on a document. I
 # have this script run via vim.
@@ -13,14 +14,15 @@ file=$(readlink -f "$1")
 dir=${file%/*}
 base="${file%.*}"
 ext="${file##*.}"
-makedir='n'
+
+git status >/dev/null && toplevel="$(git rev-parse --show-toplevel)"
 
 cd "$dir" || exit 1
 
 textype() {
 	textarget="$(getcomproot "$file" || echo "$file")"
 	echo "$textarget"
-	command="pdflatex"
+	command="lualatex"
 	( head -n5 "$textarget" | grep -qi 'xelatex' ) && command="xelatex"
 	$command --output-directory="${textarget%/*}" "${textarget%.*}"
 		grep -qi addbibresource "$textarget" &&
@@ -29,10 +31,25 @@ textype() {
 		$command --output-directory="${textarget%/*}" "${textarget%.*}"
 }
 
-if [[ "$(ls $dir | tr "[:upper:]" "[:lower:]")" =~ "makefile" ]]; then
+markdownc() {
+	if  [ -x "$(command -v lowdown)" ]; then
+		lowdown --parse-no-intraemph "$file" -Tms | groff -mpdfmark -ms -kept > "$base".pdf
+	elif [ -x "$(command -v groffdown)" ]; then
+		groffdown -i "$file" | groff > "$base.pdf"
+	elif [ -x "$(command -v pandoc)" ]; then
+		pandoc -t ms --highlight-style=kate -s -o "$base".pdf "$file"
+	else
+		echo "Could not find markdown compiler"; exit 2
+	fi ;
+}
+
+if [ -e "$(find "${dir}" -maxdepth 1 -type f -iname 'makefile')" ]; then
     make && exit 0 || exit 1
+elif [ -e "$(find "${toplevel}" -maxdepth 1 -type f -iname 'makefile')" ]; then
+	cd "${toplevel}" && make && exit 0 || exit 1
 fi
-case "$ext" in
+
+case "$(echo "${ext}" | tr '[:upper:]' '[:lower:]')" in
 	# Try to keep these cases in alphabetical order.
 	[0-9]) preconv "$file" | refer -PS -e | groff -mandoc -T pdf > "$base".pdf ;;
 	c) cc "$file" -o "$base" && "$base" ;;
@@ -42,28 +59,17 @@ case "$ext" in
 	h) sudo make install ;;
 	java) javac -d classes "$file" && java -cp classes "${1%.*}" ;;
 	m) octave "$file" ;;
-	md)	if  [ -x "$(command -v lowdown)" ]; then
-			lowdown --parse-no-intraemph "$file" -Tms | groff -mpdfmark -ms -kept > "$base".pdf
-		elif [ -x "$(command -v groffdown)" ]; then
-			groffdown -i "$file" | groff > "$base.pdf"
-		else
-			pandoc -t ms --highlight-style=kate -s -o "$base".pdf "$file"
-		fi ; ;;
 	mom) preconv "$file" | refer -PS -e | groff -mom -kept -T pdf > "$base".pdf ;;
 	ms) preconv "$file" | refer -PS -e | groff -me -ms -kept -T pdf > "$base".pdf ;;
 	org) emacs "$file" --batch -u "$USER" -f org-latex-export-to-pdf ;;
 	py) python "$file" ;;
-	[rR]md) if [ -e "./_build" ]; then
-		./_build
-	elif [ -e "../_build" ]; then
-		../_build
-	else
-		Rscript -e "rmarkdown::render('$file', quiet=TRUE)"
-	fi ;;
+	rmd) Rscript -e "rmarkdown::render('$file', quiet=TRUE)" ;;
 	rs) cargo build ;;
 	sass) sassc -a "$file" "$base.css" ;;
 	scad) openscad -o "$base".stl "$file" ;;
 	sent) setsid -f sent "$file" 2>/dev/null ;;
-	tex) textype "$file" ;;
+	md)	markdownc ;;
+	tex) textype ;;
+    mmd) mmdc --input "$file" --output "${base}.pdf" ;;
 	*) sed -n '/^#!/s/^#!//p; q' "$file" | xargs -r -I % "$file" ;;
 esac
diff --git a/bin/dmenu/dmenupass b/bin/dmenu/dmenupass
--- a/bin/dmenu/dmenupass
+++ b/bin/dmenu/dmenupass
@@ -1,6 +1,35 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-# This script is the SUDO_ASKPASS variable, meaning that it will be used as a
-# password prompt if needed.
+shopt -s nullglob globstar
 
-dmenu -fn Monospace-18 -P -p "$1" <&- && echo
+typeit=0
+if [[ $1 == "--type" ]]; then
+	typeit=1
+	shift
+fi
+
+if [[ -n $WAYLAND_DISPLAY ]]; then
+	dmenu="wofi -d"
+	xdotool="ydotool type --file -"
+elif [[ -n $DISPLAY ]]; then
+	dmenu=dmenu
+	xdotool="xdotool type --clearmodifiers --file -"
+else
+	echo "Error: No Wayland or X11 display detected" >&2
+	exit 1
+fi
+
+prefix=${PASSWORD_STORE_DIR-~/.password-store}
+password_files=( "$prefix"/**/*.gpg )
+password_files=( "${password_files[@]#"$prefix"/}" )
+password_files=( "${password_files[@]%.gpg}" )
+
+password=$(printf '%s\n' "${password_files[@]}" | $dmenu "$@")
+
+[[ -n $password ]] || exit
+
+if [[ $typeit -eq 0 ]]; then
+	pass show -c "$password" 2>/dev/null
+else
+	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
+fi
